version: '3.7'
services:
  kedro:
    container_name: {{cookiecutter.project_name}}
    build:
      context: .
      dockerfile: ./cpu.dockerfile
    command: ["honcho start $PROCESSES"]
    ports:
      - "${PORT:-2222}:8080"
      - "6006:6006"
      - "4141:4141"
    env_file:
      - .env
    volumes:
      - ${PWD}:/app/
